name: "Report"

on:
  schedule:
  - cron: '0 0 * * *'

jobs:

  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: PageSpeed Insights Audit
      uses: colbyfayock/pagespeed-insights-report-action@v1.0.6
      with:
        url: https://colbyfayock.com

    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
