name: Lighthouse

on: [push]

jobs:

  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs with Field Performance Plugin
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://www.colbyfayock.com/
