name: Performance Audit

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g @lhci/cli@0.4.x
      - run: lhci collect --url=https://gatsby-starter-pagespeed-insights-report.netlify.app
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
